//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoublePain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelllContainer : DbContext
    {
        public ModelllContainer()
            : base("name=ModelllContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Visit> VisitSet { get; set; }
        public virtual DbSet<Service> ServiceSet { get; set; }
        public virtual DbSet<TypeOfRoom> TypeOfRoomSet { get; set; }
        public virtual DbSet<Room> RoomSet { get; set; }
        public virtual DbSet<Job> JobSet { get; set; }
        public virtual DbSet<TypeOfService> TypeOfServiceSet { get; set; }
        public virtual DbSet<TypeOfPrice> TypeOfPriceSet { get; set; }
        public virtual DbSet<Client> ClientSet { get; set; }
        public virtual DbSet<Employee> EmployeeSet { get; set; }
    }
}
